### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by fpiekert** [megastruktur/foundryvtt-blades-in-the-dark#109]
Hello there!

I startet a german translation (de.json from the lang-folder) and want to test it. How do I acitvate it? I can get ie spanish to work but simply putting the german translation into the lang folder doesn't seem to work. Sorry for my bad coding skills!
warmest wishes, Fabian.

**Comment by megastruktur** [comment]
Hey @fpiekert !
You need to do 1 more thing: edit the `system.json` file and add the "DE" translation there just like the others  :)
