### ISSUE TITLE
Vault upgrades do not work

### ISSUE THREAD

**Issue by yarrriv** [megastruktur/foundryvtt-blades-in-the-dark#113]
The vault crew upgrades don't seem to work. 

More genrally I think this is an issue with the "addition" part of callItemLogic; if I generate a similar item with "attribute_change" it does add the required vault spaces.

(when I remove it they don't go away, though, so maybe an issue with undoItemLogic as well)

**Comment by megastruktur** [comment]
Can be done via Effects now.
