### ISSUE TITLE
Add +3/-3 indicators on the Factions progress trackers

### ISSUE THREAD

**Issue by r-valyar** [megastruktur/foundryvtt-blades-in-the-dark#122]
I propose to add numbers under each faction's progress tracker, to significantly improve the readability. 
A mock-up is attached as one picture says more than thousand words:

![image](https://user-images.githubusercontent.com/63558984/120353234-361ea780-c30a-11eb-96e1-3edd6e8fa16a.png)

I am not sure the purpose of the first one.

**Comment by megastruktur** [comment]
Can be done via Effects now.
