### ISSUE TITLE
Provide interface or setting to increase the stress boxes 

### ISSUE THREAD

**Issue by r-valyar** [megastruktur/foundryvtt-blades-in-the-dark#123]
Crew upgrades allow increase of the maximum stress boxes with 1 or more if house rules are used. I propose to implement interface or setting in the system to allow players to increase their stressboxes with arbitrary value. 

Example is how Roll20 addressed this. All of those can be put as settings on system level or per charsheet preferably. 
![image](https://user-images.githubusercontent.com/63558984/120353930-b7763a00-c30a-11eb-8ef0-179cd11261ad.png)

**Comment by megastruktur** [comment]
Can be done via Effects now.
