### ISSUE TITLE
All Attribute / Skill Rolls Flagged as Resolve Rolls

### ISSUE THREAD

**Issue by JoystickHero1** [megastruktur/foundryvtt-blades-in-the-dark#124]
In Blades in the Dark V. 3.0 and 3.1, I have had an issue where any roll I do prints RESOLVE as the roll made to chat. No matter if it is an attribute or skill roll. It does roll the correct number of dice and give the correct roll result for the skill or attribute actually rolled, but it does make it awkward to know what was rolled at any given time. This is with no installed modules and on Foundry v.0.8.6. 

Also want to note that Scum and Villainy works correctly for me, as well as noting that I have not tried this system in earlier versions of Foundry.

Attaching image of a 4 pip Finesse roll followed by a Prowess 1 die roll.
![image](https://user-images.githubusercontent.com/20269957/120367714-0f3e8200-c2c6-11eb-8391-af92104bc911.png)

**Comment by megastruktur** [comment]
@JoystickHero1 hey, please take a look now, should be fixed  :)  If not - please post a comment here!

**Comment by JoystickHero1** [comment]
Looks like it's fixed! Thanks for getting to this quickly!
