### ISSUE TITLE
3.5 manifest still refers to version 3.4

### ISSUE THREAD

**Issue by ghorbey** [megastruktur/foundryvtt-blades-in-the-dark#145]
Hi,

In https://raw.githubusercontent.com/megastruktur/foundryvtt-blades-in-the-dark/3.5/system.json, version is still 3.4.0, not sure it's normal. Version number wasn't updated when branch was merged.

**Comment by megastruktur** [comment]
Thanks, bro. Fixed that one just now in 3.6

**Comment by ghorbey** [comment]
Same mistake for 3.10, manifest still refers to 3.9.

Classic dev mistake btw. ;-)

**Comment by megastruktur** [comment]
@ghorbey Damn it. Too many places to change the version. I will need to write a script eventually  :D
Hold on, gonna fix it with 3.11. Thanks  :)
