### ISSUE TITLE
after 3.9 I cant Open a char sheet

### ISSUE THREAD

**Issue by brunocalado** [megastruktur/foundryvtt-blades-in-the-dark#155]
after 3.9 I cant Open a char sheet

![image](https://user-images.githubusercontent.com/4999783/135647959-9604787c-8b6d-40fa-916a-d48c4cf06be8.png)

**Comment by megastruktur** [comment]
Hey, I'm investigating the issue!

**Comment by justinross** [comment]
Thanks for the report @brunocalado. I can't seem to reproduce this issue. If you check your file system, does the specified file exist? I don't see any changes in the 3.9 update that should have changed template files/locations, but it doesn't mean I didn't miss something.

Feel free to message me on Discord, too. Might be easier to get to the bottom of this: ThsJstIn#5654

**Comment by brunocalado** [comment]
I deleted the system from the folder. Installed again. Worked.

Something went wrong with my update.

Tks

**Comment by justinross** [comment]
Megastruktur had a similar issue. I wonder if GitHub was being weird when you updated. Anyway, glad it’s working for you now. Thanks!
