### ISSUE TITLE
Faction Sheet Bug

### ISSUE THREAD

**Issue by McCurmudgeon** [megastruktur/foundryvtt-blades-in-the-dark#162]
When I remove a faction from the faction sheet It removes the faction but then locks me out from making any more changes to the sheet
I can't even open it anymore
The factionsheet is still visible in the side bar but if I click on it nothing happens

Only way to regain access to the sheet is to log out of the world and then log back in

**Comment by Arnatious** [comment]
Looks like the offending line is https://github.com/megastruktur/foundryvtt-blades-in-the-dark/blob/9e207a460285907efeb50cff9e22058ba14b5f17/module/blades-faction-sheet.js#L52, when the complete function is called, `this` refers to the actor sheet itself, which is then hidden.

**Comment by Arnatious** [comment]
Sobran and I figured it out - https://github.com/megastruktur/foundryvtt-blades-in-the-dark/blob/9e207a460285907efeb50cff9e22058ba14b5f17/module/blades-faction-sheet.js#L12 - factions incorrectly have an item class applied.
