### ISSUE TITLE
Error in the de.json translation file

### ISSUE THREAD

**Issue by KarstenW76** [megastruktur/foundryvtt-blades-in-the-dark#168]
Hi, the German translation does not work, but I found the issue, please delete twice ".

In Line 75 the both " " around the word Elite ("Elite" -> Elite) must be deleted, as these are the same as in the syntax, so the syntax gets corrupted.

Thank you!

**Comment by megastruktur** [comment]
@KarstenW76 thanks, I've fixed that one. Could you please check?  :)

**Comment by KarstenW76** [comment]
Done, works, thank you (in the name of a friend, who is playing Blades!
