### ISSUE TITLE
Add Localization

### ISSUE THREAD

**Issue by megastruktur** [megastruktur/foundryvtt-blades-in-the-dark#17]

**Comment by Cododoc** [comment]
Can you add localization support to templates. I think community can help you with translation.

Another way, give users permission to edit all text and save it. GM or players can change labels and descriptions one time and use it in the game.

**Comment by megastruktur** [comment]
Hey @Cododoc , sure thing, I just need to see how to translate items.
There is a module Babel, which helps doing it. So I take a look.

Will try to start this week  :)

**Comment by megastruktur** [comment]
Good day, sir @Cododoc !
Can you please take a look and test Localization changes at `development` branch?
Items are still not Localized (will take some time because of the additional module) but everything else should be ok.

**Comment by Cododoc** [comment]
@megastruktur Thank you. I checked it. I added translation file with small fix and changed languages settings:
```
"languages": [
    {
      "lang": "en",
      "name": "English",
      "path": "lang/en.json"
    },
    {
      "lang": "ru",
      "name": "Russian",
      "path": "lang/ru.json"
    }
  ]
```
It is looks like it work. I found that attributes localization not ready yet. Hope, it will not to hard to localize it.

**Comment by megastruktur** [comment]
@Cododoc attributes are localized, however there is a *small* problem. You need to recreate the Character  :)
I will write a migration today so all characters will be updated and make a new version.

Can you please check the layouts with russian? Also it would be awesome if you can create a pull request (from/to `development` branch) with russian translation including fonts (русские шрифты в фаундри - это просто провал, так что нужно добавить поддерживаемые шрифты).

**Comment by Cododoc** [comment]
@megastruktur Ok. I will test layouts and fonts at friday.
