### ISSUE TITLE
More Translation Options

### ISSUE THREAD

**Issue by knightje** [megastruktur/foundryvtt-blades-in-the-dark#171]
Even though there are language files for some of the abilities, there is a lot of stuff that the community can't translate without your help.
This results in having a character sheet that is semi translated and half original English.

For instance the special abilities are stored in \blades-in-the-dark\packs\abilities.db 
Is there any way you could make them modfieable so that we can translate them into different languages without having to edit the .db system files?

Vialiki dziakuj za vašyja namahanni!

**Comment by drewg13** [comment]
There's no default Foundry way to do this, but you can use a translation module called Babele to create your own translation module for compendium content.

This is the module:
https://gitlab.com/riccisi/foundryvtt-babele

and here's an example of a translation module that uses Babele to translate a similar system:
https://github.com/brunocalado/scum-and-villainy-pt-br

**Comment by megastruktur** [comment]
We have to wait until Babele becomes part of FoundryVTT core  :(
