### ISSUE TITLE
Add BitD fonts and fix styles

### ISSUE THREAD

**Issue by megastruktur** [megastruktur/foundryvtt-blades-in-the-dark#18]
- Add proper fonts
- Check styles and design of layouts
- If possible test on different locales (but EN is the priority)

**Comment by DarkWizarD24** [comment]
The main font that is missing is Kirsty. However, licence for using it on the web forbid its usage in our use case. I do not found any font that look the same, have an adapted licence and support other languages than english.

FoundryVTT comes with Modesto Condensed, it could be a good font to improve the style without licensing issues.

**Comment by justinross** [comment]
Does the license prevent its use in modules like this? Looking at the license on Font Squirrel, I'm not seeing anything that would prevent it: https://www.fontsquirrel.com/license/kirsty

It says you can't "combine fonts into a single archive", but that kind of language is usually for prohibiting people assembling font packs. 

Anyway, hope this doesn't sound argumentative. Just wondering if there's more info out there I haven't seen.

**Comment by DarkWizarD24** [comment]
I found out that the current version of the font (version 5) is has a more restictive licence than the one you found (version 2).

We can use the font you linked but not the last version that is found for example on dafont.com or typodermicfonts.com.

**Comment by justinross** [comment]
Oh nice. That seems like it'd be sufficient. Though, you're right that Modesto Condensed looks pretty great, too.

**Comment by justinross** [comment]
Okay, so, I made a fork and started with adding the fonts to the repo, then got started with implementing them, and now I've gotten carried away and have started on redoing the layout of the character sheet. So far, I've just done basic implementations of most of the basic fields, but I'm starting to get into areas where knowledge of Foundry would be useful, and conversations should probably be had regarding how to proceed (I've made some template.json adjustments on my end, for example). 

I don't want to just go off on my own (well, more than I already have) and waste a bunch of time on stuff that's not useful. Would anyone be interested in working with me on the character sheets? This is my first foray into Foundry development (I have a ton of experience with HTML/CSS and Javascript, however).

![image](https://user-images.githubusercontent.com/1120106/116481727-a2544a00-a838-11eb-8ee5-ec4e24308f12.png)

**Comment by megastruktur** [comment]
Hey @justinross , I think you could ask for help in Foundry Discord channel, Blades room. I wish I could help but unfortunately I haven't yet played Blades even once so I can't judge the UI  :(  Then when you have some work done just create a Pull Req, I will merge your changes if the community accepts your layouts  :)

**Comment by DarkWizarD24** [comment]
@justinross Can you create an issue where you share a mockup of your goal and we can talk about it. I'd be glad to help you only to work on a sheet that will end up in the main release.

**Comment by justinross** [comment]
Thanks! That’s my goal, as well. I’ll make a new issue a bit later today and we can go from there.
