### ISSUE TITLE
Update path seems to be incorrect

### ISSUE THREAD

**Issue by paradoja** [megastruktur/foundryvtt-blades-in-the-dark#201]
When trying to update the module tries to get the built module from 
https://github.com/megastruktur/foundryvtt-blades-in-the-dark/releases/download/4.6/blades-in-the-dark-4.7.zip

instead of https://github.com/megastruktur/foundryvtt-blades-in-the-dark/releases/download/4.7/blades-in-the-dark-4.7.zip

(notice the `/4.6/` vs the `/4.7/` in the path)

The error comes from here:
https://github.com/megastruktur/foundryvtt-blades-in-the-dark/blob/70ed8172c9c430de9a2d0a88bd798bfc87a0b9f5/system.json#L14

But I guess its an autogenerated line.

**Comment by megastruktur** [comment]
oh I wish it was autogenerated. Never had time to do this. Thanks I'll fix it.

**Comment by megastruktur** [comment]
Will be autogenerated in future so closing for now.
