### ISSUE TITLE
Dice so nice no longer working in 5.1.1

### ISSUE THREAD

**Issue by sorrythatuserbla** [megastruktur/foundryvtt-blades-in-the-dark#215]
![grafik](https://github.com/megastruktur/foundryvtt-blades-in-the-dark/assets/78597675/3ed949bf-49cc-4a00-80ce-392db1c387f9)

Updating to 5.1.1 caused DSN to stop showing dice on rolls from the sheets aswell as from the "Simple Roll"

**Comment by justinross** [comment]
Hi! This repo is actually no longer the source for the Blades system in foundry’s directory.

The new repo is here: https://github.com/Dez384/foundryvtt-blades-in-the-dark

I’ll look into the bug though.

**Comment by sorrythatuserbla** [comment]
Oh sorry for that.

 Maybe it's me not knowing GitHub very well, but I can't find a place in the new repo to adress issues...
 Thank you for looking into it!

**Comment by megastruktur** [comment]
@sorrythatuserbla Hello there!
Yeah you're right, there is no "Issues" tab. I'll contact the owner and ask him to create one. Thanks  :)

**Comment by Dez384** [comment]
5.1.1 was made to fix DSN not working in v12 Foundry. This may have broken it in v11 Foundry. If you are planning to stay on v11 Foundry, you may want to visit the updated repo and download version 5.0.0

**Comment by Dez384** [comment]
@sorrythatuserbla , This issue was fixed in v5.1.2 of the game system.
