### ISSUE TITLE
Tokens and character sheets don't pull up file upload/selection dialog for images

### ISSUE THREAD

**Issue by fredhicks** [megastruktur/foundryvtt-blades-in-the-dark#49]
Tokens and character sheets don't pull up file upload/selection dialog for images when I click on the image or file-icon button, so everything is stuck with default tokens & character images. :)

**Comment by fredhicks** [comment]
Hm, okay, this appears not to work on my mac local installation, but DOES work on a hosted instance on a server. Might just be a mac permissions issue.

**Comment by fredhicks** [comment]
... Or rather it did work on the hosted server for a little while, but then after I uploaded an image (checking the data directory, successfully), it started to refuse to open in-vtt file browsing dialog at all. Now I can't update character sheet image at all, and the only way I can put one on a token is by manually entering the filepath.

**Comment by megastruktur** [comment]
@fredhicks I'm not sure it's BitD-related issue, but will take a look tomorrow  :)

**Comment by fredhicks** [comment]
I didn't encounter the issue when working with my other world using D&D 5e, but I could entirely see it being a problem due to  the latest Foundry update. Best of luck on the bug hunt!

**Comment by fredhicks** [comment]
I haven't updated the module yet, but I wanted to capture here the console message I get under the prior version when I click on an image icon or file-dialog button; I'll let you know if it persists after update -- 

blades.js:67 Uncaught (in promise) TypeError: options.fn is not a function
    at Object.<anonymous> (blades.js:67)
    at Object.c (handlebars.min.js:27)
    at eval (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:10:214)
    at Object.h [as fn] (handlebars.min.js:27)
    at Object.<anonymous> (handlebars.min.js:27)
    at Object.c (handlebars.min.js:27)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:39:47)
    at c (handlebars.min.js:27)
    at d (handlebars.min.js:27)
    at e (handlebars.min.js:28)

**Comment by fredhicks** [comment]
Confirmed, that appears to have done it!
