### ISSUE TITLE
Dice rolling macro

### ISSUE THREAD

**Issue by fredhicks** [megastruktur/foundryvtt-blades-in-the-dark#51]
Don't know if it helps, but here's the javascript for a fairly robust script macro for rolling Blades style dice. Saw you had dice rolling as a pending feature, so figured I'd share in case it's of any use. Forgive any bad coding practices and the delivery method for this, I am rusty as a coder, learning javascript on the fly, and am not yet github savvy. :) 

https://www.dropbox.com/s/vc6z32qwrq3i77u/blades-roll.js?dl=0

**Comment by megastruktur** [comment]
Thanks! I will take a look  :)

**Comment by megastruktur** [comment]
@fredhicks Started working on Dice rolling. Will use parts of your script  :)

**Comment by fredhicks** [comment]
Rad! Hope it proves to be of use. :)
