### ISSUE TITLE
Ask for position and effect when rolling an action

### ISSUE THREAD

**Issue by dunderjester** [megastruktur/foundryvtt-blades-in-the-dark#54]
It's a good reminder because I find it's frequently forgotten. Bonus points if the chat output is a clickable entity that can expand to the rules of the chosen position and effect.

**Comment by megastruktur** [comment]
Hey @AlexTsr , can you please describe the situation with example?  :)

**Comment by AlexTsr** [comment]
Sure. What I mean is similar to how it's handled in the roll20 sheet. When you click to roll an action, let's say Skirmish, you get three prompts

- position (controlled, risky, desperate), 
- effect (limited, standard, great),
- bonus dice

This information is added on the chat message: 
![Screenshot_2020-07-15 Test Roll20(3)](https://user-images.githubusercontent.com/2073233/87527471-76425080-c68c-11ea-96a2-38dd643c0a35.png)

As an extra for the Foundry sheet, it would be nice if you could click the position and effect entries and get the description of what that means, for example you click risky and get this information: 
![Annotation 2020-07-15 111904](https://user-images.githubusercontent.com/2073233/87527942-21eba080-c68d-11ea-96a8-09025782929f.png)

I hope I made it clearer 😅
