### ISSUE TITLE
Броски Сопротивления

### ISSUE THREAD

**Issue by Lavncelot** [megastruktur/foundryvtt-blades-in-the-dark#61]
Броски атрибутов выдавать значениями, а не успехами

**Comment by Cododoc** [comment]
@Lavncelot 
Используйте пожалуйста Английский язык для общения. Так будет выше вероятность, что вас пойму и помогут.
Данная функция уже реализована: [https://github.com/megastruktur/foundryvtt-blades-in-the-dark#rolls](url)
Это то, что вы имели ввиду?

Same in English >>>

Please use English for communication. There is more chance that community understand you and can help.
This function has already been implemented: [https://github.com/megastruktur/foundryvtt-blades-in-the-dark#rolls](url)
Is that what you meant?

**Comment by megastruktur** [comment]
@Cododoc привет!
Мы обсудили с @Lavncelot эту фичу и я сказал, что он может создать issue на любом языке, это просто напоминалка для меня  :)

@Lavncelot Но я вот сейчас перечитал и могу сказать, что это недопонимание в правилах и обсуждение поздней ночью  :)
Бросок на резисты не всегда успешен. Поэтому у нас есть и значения, и результат. Так что я закрою тикет пока что.
