### ISSUE TITLE
Traumas as Inputs

### ISSUE THREAD

**Issue by megastruktur** [megastruktur/foundryvtt-blades-in-the-dark#68]
Make Traumas as Inputs instead of checkboxes/labels.

This will help to:
- Track Traumas as Ghost/Hull
- Create custom Traumas

**Comment by thadrine** [comment]
Trauma does not work in 0.7.4. 
If you click any Trauma it auto-fill all Trauma boxes, and no longer highlights the Trauma selected.

**Comment by megastruktur** [comment]
@thadrine I've fixed that issue in Blades v. 2.5. Please make sure you use the latest version of the game system  :)

**Comment by thadrine** [comment]
Ok, any idea why Foundry will not update it beyond 2.4?

**Comment by megastruktur** [comment]
@thadrine I've created a new issue for that. Thanks for the feedback! Will take a look tomorrow.
