### ISSUE TITLE
[Bug] Removal of dice icons next to Insight/Prowess/Resolve causes each check to reset XP counters

### ISSUE THREAD

**Issue by r-valyar** [megastruktur/foundryvtt-blades-in-the-dark#71]
The last update removed the dice icon next to Insight/Prowess/Resolve. The dice was used to roll each of the stats, but now clicking the stat name also resets the XP flags.

**Comment by megastruktur** [comment]
Thanks @r-valyar , I will take a look tomorrow. There were significant changes in the system so I'm afraid I could break something.

Can you please try to create a new Character and see whether the problem still present?

**Comment by r-valyar** [comment]
Yes, this happens also to new characters. Clicking each of the attributes resets the XP counter.
