### ISSUE TITLE
[Cohorts] Missing Descriptions

### ISSUE THREAD

**Issue by WallaceMcGregor** [megastruktur/foundryvtt-blades-in-the-dark#72]
Hi.

I found a small error in the sheet. The descriptions of some things in the Cohorts are missing. In the translation file, the "BITD.GangTypeXXXDescription" elements are not even there, but the BITD.EdgesXXXDescription are.

![FoundryVTT_2020-09-04_09-04-22](https://user-images.githubusercontent.com/17795541/92209711-c324f500-ee8d-11ea-84ea-a470c408bc52.png)

**Comment by megastruktur** [comment]
FIxed in 2.2  :)
