### ISSUE TITLE
[Bug] Game system does not update automatically

### ISSUE THREAD

**Issue by r-valyar** [megastruktur/foundryvtt-blades-in-the-dark#75]
Since 2-3 releases I noticed that the game system does not update automatically when new version is out. I have 2.1 and when I check for update, Foundry reports as updated. Which is not the case, as 2.2 is already out and visible in the "Install game systems" list. In Discord it is mentioned that the fix has to be done here on manifest side.

![Annotation 2020-09-05 100447](https://user-images.githubusercontent.com/63558984/92299904-43fff180-ef5f-11ea-9ac1-bee5c06d1d00.jpg)

**Comment by megastruktur** [comment]
Hey @r-valyar ,
Maybe that's a kind of cache issue of some kind? I have all updated at my end:
![image](https://user-images.githubusercontent.com/2911416/92374227-1c985880-f108-11ea-882d-5c9856bfc2c0.png)

Which Foundry version do you have?
Can you backup your world Data and reinstall the system?

**Comment by r-valyar** [comment]
Hi, @megastruktur 

The system version was 2.1 even after check for update. When I uninstall and re-install all is good. The update does not work. 

I am using Foundry 0.6.6 from the Stable release branch.

**Comment by philote** [comment]
I am seeing the same thing on Foundry VTT 0.6.6. 
My Blades Game System is a 2.0, if I click update foundry says it is up to date.

**Comment by megastruktur** [comment]
Seems like it's the issue with 0.6.x versions. I'm on a 0.7.1. Gonna restrict < 0.7.x from next release because there was a significant refactoring done on FoundryVTT side and I won't be able to support legacy  :( 
If anybody can confirm it works on 0.7.x?
