### ISSUE TITLE
[Bug] Delete button for abilities and loadout not working correctly

### ISSUE THREAD

**Issue by philote** [megastruktur/foundryvtt-blades-in-the-dark#76]
When I try to delete items from a character sheet, under the Abilities and Loadout tabs, the list flashes but the items are not removed most of the time. However if I refresh the browser window, the items are gone. Odd thing of note, if I open Chrome's dev tools with the Console the delete works slightly more reliably, though the last item in the list never gets removed (unless I refresh). Let me know if any other info would be helpful.

**Foundry:**
0.6.6

**Blades Game System:**
2.2

**Machine:** Windows 10
Version	10.0.18362 Build 18362

**Tested on Chrome**
Version 85.0.4183.102 (Official Build) (64-bit)

**And Firefox**
80.0.1 (64-bit)

Attached a zipped video.
[FoundryVTT-Blade_bug.zip](https://github.com/megastruktur/foundryvtt-blades-in-the-dark/files/5211836/FoundryVTT-Blade_bug.zip)

**Comment by megastruktur** [comment]
Managed to reproduce the bug. Will investigate!  :)
