### ISSUE TITLE
Make Skills responsive

### ISSUE THREAD

**Issue by WallaceMcGregor** [megastruktur/foundryvtt-blades-in-the-dark#77]
Hi

I've seen a little bug when I select Spanish. Skills are not responsive and they are covered by the XP buttons.

![BitD Foundry Bug](https://user-images.githubusercontent.com/17795541/93298542-ad032700-f7f3-11ea-9a67-a3d744743275.png)

**Comment by megastruktur** [comment]
Oh that's quite a bug. Gonna take a look.

**Comment by megastruktur** [comment]
Okay. I've managed to take a look and what I'm going to say: making text responsive breaks the overall look.

@WallaceMcGregor Could you please help me and make skill names shorter? Something like "PRESP." and "VOLUN." so that it will be readable. I will add them to translation.

**Comment by WallaceMcGregor** [comment]
Ok. It is not the most "fancy" thing, but if there is no other option you can use: "PER.", "DES." & "VOL.".
