### ISSUE TITLE
I make the translation of the compendium to Spanish

### ISSUE THREAD

**Issue by warlord29a** [megastruktur/foundryvtt-blades-in-the-dark#79]
Hello, I have translated the compendia into Spanish using the official translation of the publishing house "Nosolorol". I send you the files in case you want to include them, I don't understand much of these things so I have directly edited the .db files. Regards.

[Blades in the dark traducción español.zip](https://github.com/megastruktur/foundryvtt-blades-in-the-dark/files/5232445/Blades.in.the.dark.traduccion.espanol.zip)

**Comment by megastruktur** [comment]
Hey bro!
Yeah, @WallaceMcGregor had contacted me regarding your translation several hours ago. Unfortunately there is no way I can use translated db files (the FoundryVTT system doesn't have tools for that, you can swap them manually in your installation if you wish though).
Wallace is going to make a Babele translation (it's a third-party module which allows compendium translations) and I hope he will share it with the community  :D
