### ISSUE TITLE
Text for partial success / failure always shows desperate text

### ISSUE THREAD

**Issue by colinm-omnifederal** [megastruktur/foundryvtt-blades-in-the-dark#80]
blades-roll.html is expecting "controlled" or "risky" as the position: 

```
      {{#if (eq position "controlled")}}
      {{{localize "BITD.RollFailurePositionControlled"}}}
      {{else if (eq position "risky")}}
      {{{localize "BITD.RollFailurePositionRisky"}}}
      {{else}}
      {{{localize "BITD.RollFailurePosition"}}}
      {{/if}}
```

However, blades-roll.js is passing in the localized key:

```
  switch (position) {
    case 'controlled':
      position_localize = 'BITD.PositionControlled'
      break;
    case 'desperate':
      position_localize = 'BITD.PositionDesperate'
      break;
    case 'risky':
    default:
      position_localize = 'BITD.PositionRisky'
  }
...
let result = await renderTemplate("systems/blades-in-the-dark/templates/blades-roll.html", {rolls: rolls, roll_status: roll_status, attribute_label: attribute_label, position: position_localize, effect: effect_localize});
```

So the result is that there is never a match and it always shows the default (desperate) text.

**Comment by Malfhast** [comment]
{{#if (eq roll_status "partial-success")}}
  <div class="die {{roll_status}}">{{localize "BITD.RollPartialSuccess"}}</div>
  <div class="description">
    <p>
      {{#if (eq position "BITD.PositionControlled")}}
      {{{localize "BITD.RollPartialSuccessPositionControlled"}}}
      {{else if (eq position "BITD.PositionRisky")}}
      {{{localize "BITD.RollPartialSuccessPositionRisky"}}}
      {{else if (eq position "BITD.PositionDesperate")}}
      {{{localize "BITD.RollPartialSuccessPositionDesperate"}}}
      {{else}}
      {{{localize "BITD.RollPartialSuccessPosition"}}}
      {{/if}}
    </p>
  </div>
  {{/if}}


  {{#if (eq roll_status "failure")}}
  <div class="die {{roll_status}}">{{localize "BITD.RollFailure"}}</div>
  <div class="description">
    <p>
      {{#if (eq position "BITD.PositionControlled")}}
      {{{localize "BITD.RollFailurePositionControlled"}}}
      {{else if (eq position "BITD.PositionRisky")}}
      {{{localize "BITD.RollFailurePositionRisky"}}}
      {{else if (eq position "BITD.PositionDesperate")}}
      {{{localize "BITD.RollFailurePositionDesperate"}}}
      {{else}}
      {{{localize "BITD.RollFailurePosition"}}}
      {{/if}}
    </p>
  </div>
  {{/if}}

I did this in my "blades-roll.html".
No problem for me now

**Comment by colinm-omnifederal** [comment]
That's what I did too. When I'm less busy I'll put in a merge request if you don't beat me to it. =P

**Comment by Malfhast** [comment]
And yes, i'd changed something else, not only "Blades-roll.htlm" but : "blades-in-the-dark/lang/en.json" ->
```
BITD.RollPartialSuccessPositionControlled": "Vous hésitez. Retirez-vous et essayez une approche différente, ou faites-le avec une conséquence mineure: une <strong>Complication mineure</strong> apparait, vous avez un <strong>effet réduit</strong>, vous souffrez d'une <strong>blessure mineure</strong>, Vous vous retrouvez dans une position <strong>risquée</strong>.",
  "BITD.RollPartialSuccessPositionRisky": "Vous réussissez, mais avec une conséquence: vous souffrez d'une <strong>blessure</strong>, une <strong>complication</strong> se produit, Vous avez un <strong>Effet réduit</strong>, vous vous retrouvez dans une position <strong>désespérée</strong>.",
  "BITD.RollPartialSuccessPositionDesperate": "Vous réussissez, mais avec une conséquence: vous subissez une <strong>Blessure grave</strong>, une <strong>sérieuse complication</strong> apparait, vous avez un <strong>effet réduit</strong>.",
  "BITD.RollFailurePositionControlled": "Vous hésitez. Vous pouvez persévérer en saisissant une opportunitée <strong>Risquée</strong>, ou battez en retraite et essayer une approche différente.",
  "BITD.RollFailurePositionRisky": "Les choses tournent mal. vous subissez une <strong>blessure</strong> une <strong>complication</strong> se produit, vous vous retrouvez dans une position <strong>désespérée</strong>, vous <strong>perdez cette opportunité</strong>.",
  "BITD.RollFailurePositionDesperate": "Le pire se produit. Vous souffrez d'une <strong>blessure grave</strong>, une <strong>sérieuse complication</strong> se produit, vous <strong>perdez cette opportunité</strong>.",

```

![image](https://user-images.githubusercontent.com/70017830/93538783-472bb200-f94f-11ea-97b6-7f6fb927cc26.png)

theses ones : "BITD.RollFailurePosition" to "BITD.RollFailurePositionDesperate"

**Comment by megastruktur** [comment]
@colinm-omnifederal  @Malfhast Sorry guys, I'm sooo busy this week, gonna review and add it to 2.4 on the weekend  :)

**Comment by Malfhast** [comment]
No problem @megastruktur I even translated your code in french for my part.
and from what I saw ; It's pretty good ! ^^ good job
