### ISSUE TITLE
Traumas borked

### ISSUE THREAD

**Issue by OctarineSourcerer** [megastruktur/foundryvtt-blades-in-the-dark#81]
- Create a new actor. It seems to start with one trauma (one tooth is red on the sheet).
- Put new pips in ANYTHING multibox - be it coins, a skill, skill XP... and traumas will appear to max out.
- Clicking a trauma in the list flashes it red, and then it immediately reverts. 

As far as I can tell, the trauma-boxes-maxed is an issue with the `traumacounter` handlebars helper. Change `var count = selected.length;` to `var count = selected.filter(hasTrauma => hasTrauma).length;` apears to solve that part of it. I think selecting any of the multiboxes automatically converts the starting traumas list (`[0]`) to a list of which traumas are selected (eg `[false, false, false]`) and then the trauma counter uses the full length of that list, even though it's all false.)

Unfortunately, there still remains an issue with selecting traumas - there only seems to be one trauma active at any given time. Click vicious, it's that one set to true in the actor's `data.traumas.list`. Click soft, and then only that trauma is set. I'm not entirely sure what's up there, and I'm not sure where `data.traumas.list` is actually set. I'd be happy to help sort it if I was given pointers there.

EDIT: Should have added this in the initial bug report: I'm using Foundry 0.73, on the beta channel.

**Comment by megastruktur** [comment]
Hi @OctarineSourcerer , I will take look, thanks!  :)

**Comment by megastruktur** [comment]
Ah that's the issue of a new FVTT version. Gonna make an update with Blades 2.5
