### ISSUE TITLE
Add Clocks

### ISSUE THREAD

**Issue by megastruktur** [megastruktur/foundryvtt-blades-in-the-dark#82]
Right now there is no "Clocks" module available at FVTT.
The task is to create an extension to Blades system with clocks support. Possibly add a new menu.

Clocks should have:
- Name
- Clock Entity
- User should be able to open several Clocks at a time

https://thealexandrian.net/wordpress/40424/roleplaying-games/blades-in-the-dark-progress-clocks - can be helpful

**Comment by r-valyar** [comment]
I would push this one in high priority, clocks are key part of the meta-game in Blades! :)
