### ISSUE TITLE
Playbook XP and others get applied to most first opened character, not clicked character

### ISSUE THREAD

**Issue by drxzcl** [megastruktur/foundryvtt-blades-in-the-dark#83]
Steps to reproduce:
 
1.  Open character sheet 1
2.  Open character sheet 2
3.  Click on character sheet 2 to add playbook XP
4.  See that is it added to character sheet 1 instead

This is with the current version installed, version 2.4

Other affected values:
* Stress
* Stash
* Coin
* Healing clock
* Insight/prowess/resolve XP
* Traits (hunt, study etc)

Not affected:
* Trauma
* Armor
* Harm

**Comment by megastruktur** [comment]
Wow quite a bug. Just reproduced it myself. Gonna investigate  :D
