### ISSUE TITLE
Not able to upgrade

### ISSUE THREAD

**Issue by megastruktur** [megastruktur/foundryvtt-blades-in-the-dark#86]
Several people reported they couldn't upgrade from prev. versions: they just didn't have an option to upgrade.
Investigate wtf.

**Comment by drxzcl** [comment]
I installed from the menu in Foundry, and my system.json is linked hard to the 2.4 version:

https://raw.githubusercontent.com/megastruktur/foundryvtt-blades-in-the-dark/2.4/system.json

This ensures that i never see the upgrade.

**Comment by megastruktur** [comment]
@drxzcl the thing is that I add new versions through foundry Module Admin area. I specify all versions there with absolute paths. Previously it handled update automatically (Foundry re-downloads the whole system code dir with the new system.json if your installed version is different from the latest one and your Foundry installation meets version requirements).
Which FVTT version do you have?

**Comment by megastruktur** [comment]
By the way with FVTT 0.7.4 updating works fine. Just tested it on my local machine.

**Comment by drxzcl** [comment]
I upgraded Foundry from 0.6.6 (no upgrade visible) to 0.7.5 (still no upgrade visible). After it edited my system.json to point to the 2.5 system.json I could upgrade without problems. I'm not sure how the admin area works.

**Comment by dankrause** [comment]
The reason upgrading isn't working properly is here:

https://github.com/megastruktur/foundryvtt-blades-in-the-dark/blob/master/system.json#L34

@megastruktur - Take a look at how other systems do this:

- [DnD5e](https://gitlab.com/foundrynet/dnd5e/-/blob/master/system.json#L97)
- [Dungeon World](https://gitlab.com/asacolips-projects/foundry-mods/dungeonworld/-/blob/master/system.json#L306)
- [Fate](https://github.com/Sk1mble/modularFate/blob/master/system.json#L29)
- [SWADE](https://gitlab.com/florad-foundry/swade/-/blob/master/src/system.json#L68)

You'll note that none of them have a manifest URI in their system.json file that points to a specific release of their system. They all point to master. If I'm understanding this correctly, you always need your system.json file to have a URI that will always be updated with the latest manifest. It doesn't have to be master, but it has to be a single URI that updates when there's a new release.

**Comment by drxzcl** [comment]
@dankrause You can also bump the version number on the 2.4 branch. This will prompt an upgrade.
