### ISSUE TITLE
Cohort Type Bugs Out

### ISSUE THREAD

**Issue by OneProudBavarian** [megastruktur/foundryvtt-blades-in-the-dark#87]
[This gif showcases](https://user-images.githubusercontent.com/73198170/96639605-40170b80-1322-11eb-9116-9fdcfb9a264f.gif) that the cohort type interface bugs out on my end when selecting anything in its sheet.
The cohort type section will entirely disappear.

Keep up the amazing work!

We are on 0.7.4 of Foundry and 2.5 of BitD!

**Comment by megastruktur** [comment]
Gonna take a look tomorrow! Looks like I know what's wrong there.
