### ISSUE TITLE
Unable to reset clocks

### ISSUE THREAD

**Issue by SomeOldPirate** [megastruktur/foundryvtt-blades-in-the-dark#89]
I'm currently unable to reset any of the clocks in game, including the healing clock on the character sheet.  Clicking the reset button completely fills the clock instead of emptying it.  Using BitD 2.9 and Foundry 0.7.6.

**Comment by megastruktur** [comment]
@SomeOldPirate oh yeah bro, I'm aware of this bug  :(
This happens in Chrome (Firefox works fine). Gonna investigate it as soon as I have some time  :)
