### ISSUE TITLE
Unable to select more than 1 Edge/Flaw

### ISSUE THREAD

**Issue by supernovajm** [megastruktur/foundryvtt-blades-in-the-dark#91]
When I select the first Edge/Flaw, it takes 2 clicks, then turns red. But clicking any additional options deselects the first choice. 

![capture-2020-11-28_20 06 37](https://user-images.githubusercontent.com/24704061/100529414-77949580-31b5-11eb-9cba-ecfebeb90b75.gif)

**Comment by megastruktur** [comment]
FoundryVTT doesn't know that checkboxes can get the actual value instead of just boolean. Previously I'd added custom validators but now it won't work. Gonna invent something again.
