### ISSUE TITLE
Can't add clocks

### ISSUE THREAD

**Issue by LorduFreeman** [megastruktur/foundryvtt-blades-in-the-dark#92]
No actor type "clock" is showing when trying to create a new actor. Just character and crew.

**Comment by megastruktur** [comment]
Hey bro,
can you please make sure you have the latest version of Blades system (2.10), FoundryVTT version >0.7.2.

**Comment by LorduFreeman** [comment]
![image](https://user-images.githubusercontent.com/72170114/101018821-5c86a480-356c-11eb-87ae-986adb6c1ea5.png)

That was it, my system showed Blades 2.5 as current and updated. Did you change something like the manifests location? Reinstall fixed this.

**Comment by megastruktur** [comment]
@LorduFreeman  there was an issue with update, I've fixed it in `2.6` release  :)
