### ISSUE TITLE
Sheet for tracking "Faction Status"

### ISSUE THREAD

**Issue by BitforceRevelator** [megastruktur/foundryvtt-blades-in-the-dark#94]
Hey guys

I think it would be helpful to have a sheet where you can track the Faction Standing (Reputation) with other factions. This sheet is already available in the SRD player handout.

**Comment by megastruktur** [comment]
@BitforceRevelator I think it's a nice idea! Can you please post me a link to that doc here? Or better an image of that particular Faction Standing page.

Sorry, I do all the work on the system alone so there can be delays  :D

(_Anyway I'll mark that on as a "Good first issue". Maybe that'll inspire someone to take a look and make a PR_)

**Comment by BitforceRevelator** [comment]
Here you go: https://bladesinthedark.com/sites/default/files/blades_playerkit_v8_2.pdf

**Comment by BitforceRevelator** [comment]
It also includes the Prison Claims table btw.

**Comment by TokeVFA** [comment]
If all the factions are ever created as series of Faction 'Actors' this might come in handy as well:
https://bitd.gplusarchive.online/2017/05/12/faction-tokens/
These are some hexagonal Faction 'tokens' with the starting tier of the factions printed on them.

My reasoning behind implementing Factions as an actor or item type is to be able to link more notes, and tokens to them if need be.
