### ISSUE TITLE
Bug when selecting turf connections for custom crew

### ISSUE THREAD

**Issue by BitforceRevelator** [megastruktur/foundryvtt-blades-in-the-dark#95]
When I try to create new custom crew, and I want to set the turf connections via the checkboxes, I can't set any of them to true, they will instantly deselect.

**Comment by BitforceRevelator** [comment]
This may be related to Issue #91, as it seems to behave similarly.

**Comment by megastruktur** [comment]
@BitforceRevelator Yeah you're right, these issues are connected however it's easier for you to just copy the existing one and edit connections through text editor than to fix it.  :D

I will think about it tomorrow. Maybe I'll find a way to overcome.

**Comment by BitforceRevelator** [comment]
I tried to do it via editing the text, and setting the values to TRUE; but it did not work.
