### ISSUE TITLE
Dice So Nice! not showing to other players (fix included)

### ISSUE THREAD

**Issue by JiDW** [megastruktur/foundryvtt-blades-in-the-dark#98]
Hello!

I'm the author of the 'Dice So Nice' module. First, I'd like to thank you for implementing DsN into your system!

One player of your system sent me a report related to DsN that prevents other players from seeing rolls on their screens. Only the player rolling the dice can see them.

After a quick check, it appears to be caused by the use of the "showForRoll" method in this file: https://github.com/megastruktur/foundryvtt-blades-in-the-dark/blob/master/module/blades-roll.js#L30

By default, this method will only show the dice to the current player.

To fix this, there are two possibilities: 
- Add all the needed parameters to "showForRoll" as described in our docs: https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/wikis/API/Roll#using-the-fvtt-roll-class
- (Recommended) If you are already using a "roll" object, attaching it to your chat message will automate everything for you, and you won't need to add any DsN-specific code: https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/wikis/Integration

Regards.

**Comment by megastruktur** [comment]
@JiDW hey!

Thank you for your feedback and investigation  :)  I gonna take a look.
